pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    def githubToken = gradle.hasProperty('githubToken') ? gradle.properties['githubToken'] : System.getenv('GITHUB_TOKEN') ?: 'default_token_if_needed'
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
            credentials {
                username = "LuminSoft"
                password = githubToken
            }
        }
    }
}
rootProject.name = "ekyc-android"
include ':app'
include ':eNROLL-sdk'
