pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
            credentials {
                username = "LuminSoft"
                password = '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'
            }
        }
    }
}
rootProject.name = "ekyc-android"
include ':app'
include ':eNROLL-sdk'
